### ISSUE TITLE
build_kmstool_enclave_cli.sh stuck on cargo build step

### ISSUE THREAD

**Issue by edwardysun** [aws-samples/aws-nitro-enclave-blockchain-wallet#29]
I've been trying to run & deploy the sample, but consistently getting stuck when running the build_kmstool_enclave_cli.sh script on ` => [builder 37/48] RUN source $HOME/.cargo/env && cd aws-nitro-enclaves-nsm-api && cargo build --release --jobs   561.2s` -- tried increasing memory on Docker but still no luck. Any suggestions on what to do from here?

**Comment by wgr2017** [comment]
Hi @edwardysun thanks for reaching out. I was able to replicate the issue, and it seems it is happening due to lack of storage. I got the following error: "error: couldn't create a temp dir: No space left on device (os error 28) at path "/tmp/rustcNDlKwR". I then increased the EBS volume size attached to my Cloud9 instance from 10GB to 30GB using the instructions provided [here](https://docs.aws.amazon.com/ebs/latest/userguide/ebs-modify-volume.html). After that, I ran the build again, and it was successful. Please let me know if this solves your issue as well.
